__title__ = "interva"
__description__ = "Python implementation of the InterVA Algorithm."
__url__ = "https://github.com/verbal-autopsy-software/interva"
__version__ = "0.0.1"
__author__ = "Sherry Zhao, Jason Thomas"
__author_email__ = "jarathomas@gmail.com"
__license__ = "GPLv3"
